In [26]:
import pandas as pds
dns = pd.read_csv('resolver_data.csv', names=['status','resolver','name','time','size','datetime'])

In [27]:
dns.head(500)

,status,resolver,name,time,size,datetime
0,ok,https://dns.google/dns-query,google.com,81.525917,44,Mon Jun 28 21:36:27 2021
1,ok,https://dns.google/dns-query,netflix.com,82.448855,77,Mon Jun 28 21:36:27 2021
2,ok,https://dns.aa.net.uk/dns-query,google.com,482.781316,44,Mon Jun 28 21:36:28 2021
3,ok,https://dns.aa.net.uk/dns-query,netflix.com,492.412777,213,Mon Jun 28 21:36:28 2021
4,ok,https://adfree.usableprivacy.net/dns-query,google.com,440.363424,124,Mon Jun 28 21:36:28 2021
...,...,...,...,...,...,...
495,ok,https://doh.dns.sb/dns-query,google.com,154.240851,65,Mon Jun 28 21:47:03 2021
496,ok,https://doh.dns.sb/dns-query,netflix.com,170.777424,121,Mon Jun 28 21:47:03 2021
497,error,netflix.com,810.077098,8,NaN,NaN
498,error,google.com,810.423576,8,NaN,NaN
499,Query failed: SSL connect error,https://dns1.dnscrypt.ca/dns-query,google.com,,,Mon Jun 28 21:47:04 2021

In [28]:
dns['status'].unique()
dns['time'] = dns['time'].astype(float)

ValueError: could not convert string to float: ''

In [43]:
dns_ok_google = dns[(dns['status']=='ok') & (dns['name']=='google.com')]
dns_ok_google['time'] = dns_ok_google['time'].astype(float)

<ipython-input-43-3e7410b7b88e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dns_ok_google['time'] = dns_ok_google['time'].astype(float)

In [44]:
dns_ok_google['time'].describe()

count     6039.000000
mean       673.577658
std       3029.461819
min         40.703876
25%        114.955647
50%        340.237601
75%        537.513175
max      40385.770802
Name: time, dtype: float64

In [47]:
dns_ok_google['resolver'].unique()

array(['https://dns.google/dns-query', 'https://dns.aa.net.uk/dns-query',
       'https://adfree.usableprivacy.net/dns-query',
       'https://dns.adguard.com/dns-query',
       'https://dns-family.adguard.com/dns-query',
       'https://doh.in.ahadns.net/dns-query',
       'https://doh.la.ahadns.net/dns-query',
       'https://doh.nl.ahadns.net/dns-query',
       'https://dns.alidns.com/dns-query',
       'https://dnsnl.alekberg.net/dns-query',
       'https://dns.arapurayil.com/dns-query',
       'https://dohtrial.att.net/dns-query',
       'https://dnses.alekberg.net/dns-query',
       'https://dns.circl.lu/dns-query',
       'https://doh.opendns.com/dns-query',
       'https://dns.cloudflare.com/dns-query',
       'https://family.cloudflare-dns.com/dns-query',
       'https://security.cloudflare-dns.com/dns-query',
       'https://odvr.nic.cz/dns-query',
       'https://dns.digitale-gesellschaft.ch/dns-query',
       'https://dns1.ryan-palmer.com/dns-query',
       'https://doh.dns.sb/dns-query',
       'https://dns-doh.dnsforfamily.com/dns-query',
       'https://dns-doh-no-safe-search.dnsforfamily.com/dns-query',
       'https://dnsforge.de/dns-query',
       'https://dns.dnshome.de/dns-query', 'https://doh.pub/dns-query',
       'https://doh-ch.blahdns.com/dns-query',
       'https://doh-de.blahdns.com/dns-query',
       'https://doh-fi.blahdns.com/dns-query',
       'https://ibksturm.synology.me/dns-query',
       'https://doh-jp.blahdns.com/dns-query',
       'https://doh-sg.blahdns.com/dns-query',
       'https://doh.ffmuc.net/dns-query',
       'https://doh.tiarap.org/dns-query',
       'https://ordns.he.net/dns-query',
       'https://public.dns.iij.jp/dns-query',
       'https://doh.this.web.id/dns-query',
       'https://jp.tiarap.org/dns-query',
       'https://doh.libredns.gr/dns-query',
       'https://doh.linuxsec.org/dns-query',
       'https://adblock.doh.mullvad.net/dns-query',
       'https://doh.mullvad.net/dns-query',
       'https://dns.nextdns.io/dns-query',
       'https://dns.njal.la/dns-query',
       'https://draco.plan9-ns2.com/dns-query',
       'https://doh.powerdns.org/dns-query',
       'https://doh-2.seby.io/dns-query',
       'https://dns.twnic.tw/dns-query',
       'https://dns9.quad9.net/dns-query',
       'https://dnsse.alekberg.net/dns-query',
       'https://dns.switch.ch/dns-query', 'https://dns.t53.de/dns-query',
       'https://sg.yepdns.com/dns-query'], dtype=object)

In [49]:
test = dns_ok_google[dns_ok_google['resolver']=='https://ibksturm.synology.me/dns-query']

In [50]:
test.describe()

              time
count   102.000000
mean    964.357133
std    1007.088864
min     595.066297
25%     619.145533
50%     650.279892
75%     689.974992
max    6790.587578

In [51]:
test2 = dns_ok_google[dns_ok_google['resolver']=='https://dns.google/dns-query']

In [52]:
test2.describe()

             time
count  203.000000
mean    52.198364
std     12.847168
min     42.901915
25%     45.977472
50%     47.047326
75%     49.222607
max    118.274524